name: Post to a Slack channel
on:
  workflow_dispatch: {}
jobs:
  build:
    name: Send data to Slack
    runs-on: ubuntu-latest
    steps:
    # Checkout (without LFS)
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Post to a Slack channel
        
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
  
        with:
    # Slack channel id, channel name, or user id to post message.
    # See also: https://api.slack.com/methods/chat.postMessage#channels
    # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
          channel-id: 'C05CEJXA3EH'
    # For posting a simple plain text message
          slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        env:
            SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
